name: Create combined zip file

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install zip
      run: sudo apt-get update && sudo apt-get install -y zip

    - name: Create combined zip file
      run: |
        mkdir zips
        ls 
        pwd
        cp /home/runner/work/poc/poc/requirement.txt zips
        zip -r combined.zip zips
        echo "name=combined.zip" >> $GITHUB_OUTPUT

      id: create_zip

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: combined-zip
        path: ${{ steps.create_zip.outputs.zip-filename }}

