name: Create combined zip file

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install zip
      run: sudo apt-get update && sudo apt-get install -y zip

    - name: Create combined zip file
      run: |
        pwd
        ls -l
        zip -r combined.zip requirement.txt triangle.py
        echo "::set-output name=combined_zip::combined.zip"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: combined-zip
        path: combined.zip
