name: Create combined zip file

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install zip
      run: sudo apt-get update && sudo apt-get install -y zip

    - name: Create combined zip file
      run: |
        ls
        zip -r combined.zip . -i aip.zip aip1.zip
        echo "name=combined.zip" >> $GITHUB_OUTPUT


    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: combined-zip
        path: combined.zip


